config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'

  get "ads/new_ads"
  get "ads/archive_ads"
  get "ads/approved_ads"
  get "admin_actions/deny"
  get "admin_actions/approve"
  get "user_actions/to_draft"
  get "user_actions/to_new"
  get "ads/myads", to: "ads#myads"

  devise_for :users
  resources :users
  resources :ads
  resources :ads_types
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  validates :ads_type_id, :user_id, :presence => true
  has_many_attached :images

  state_machine :initial => :draft do
    state :draft, :value => 1
    state :new, :value => 2
    state :denied, :value => 3
    state :approved, :value => 4
    state :published, :value => 5
    state :archived, :value => 6

    event :to_draft do
      transition [:denied, :archived] => :draft
    end

    event :to_new do
      transition :draft => :new
    end

    event :deny do
      transition :new => :denied
    end

    event :approve do
      transition :new => :approved
    end

    event :publish do
      transition :approved => :published
    end

    event :archive do
      transition :published => :archived
    end

  end
end

app/models/ads_type.rb
class AdsType < ApplicationRecord
  validates :name, :uniqueness => true
  has_many :ads, :dependent => :restrict_with_error
  before_destroy :check_ads_count, :check_last_type

  def check_ads_count
    ads.count == 0
  end

  def check_last_type
    AdsType.count > 1
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  def index
    @ads = Ad.with_states(:published).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @types = AdsType.all
    respond_to do |format|
      format.html
      format.json { render :json => @ads }
    end
  end

  def show

    @ad = Ad.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @ad }
    end
  end

  def new
    @ad = Ad.create :ads_type_id => AdsType.first.id, :user_id => current_user.id, :state => 1
    @ads_types = AdsType.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ad }
    end
  end

  def edit
    @ad = Ad.find(params[:id])
    @ads_types = AdsType.all
  end

  def create
    @ad = Ad.new(params[:ad])
    respond_to do |format|
      if @ad.save and @ad.images.attach(params[:ad][:images])
        format.html { redirect_to @ad, :notice => 'Ad was successfully created.' }
        format.json { render :json => @ad, :status => :created, :location => @ad }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ad.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @ad = Ad.find(params[:id])
    @ads_types = AdsType.all
    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to @ad, :notice => 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ad.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end

  def myads
    @ads = Ad.where(:user_id => current_user.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 10) #sort, paginate
    @types = AdsType.all
    respond_to do |format|
      format.html
        format.json { render :json => @ads }
    end
  end

  def new_ads
    @ads = Ad.with_states(:new).order("created_at DESC").paginate(:page => params[:page], :per_page => 10) #sort, paginate
    @types = AdsType.all
    respond_to do |format|
      format.html
      format.json { render :json => @ads }
    end
  end

  def archive_ads
    @ads = Ad.with_states(:archived).order("created_at DESC").paginate(:page => params[:page], :per_page => 10) #sort, paginate
    @types = AdsType.all
    respond_to do |format|
      format.html
      format.json { render :json => @ads }
    end
  end

  def approved_ads
    @ads = Ad.with_states(:approved).order("created_at DESC").paginate(:page => params[:page], :per_page => 10) #sort, paginate
    @types = AdsType.all
    respond_to do |format|
      format.html
      format.json { render :json => @ads }
    end
  end

  def ad_params
    params.require(:ad).permit(:name,:description,:ads_type_id, images: [])
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  def get_ads_types(ads_types)
    ads_types.map { |t| [t.name, t.id] }
  end

  def get_name_of_type types, id
    types.each do |type|
      if type[:id] == id
        return type[:name]
      end
    end
  end
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :ads_type_id, get_ads_types(@ads_types) %>
  </div>
  <div class="field">
    <%= f.file_field :images, multiple: true %><br>
  </div>
  <div class="actions">
    <%= f.submit 'Update Ad'%>
  </div>
<% end %>

app/views/ads/approved_ads.html.erb
<h1>Listing new ads</h1>

<table border="1">
  <tr>
    <th>Description</th>
    <th>Name</th>
    <th>Status</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ads.each do |ad| %>
  <tr>
    <td><%= ad.description %></td>
    <td><%= ad.name %></td>
    <td><%= ad.state_name %></td>
    <td><%= get_name_of_type(@types, ad.ads_type_id.to_i)%></td>
    <td><%= link_to 'Show', ad %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @ads %>
<br />

app/views/ads/archive_ads.html.erb
<h1>Listing new ads</h1>

<table border="1">
  <tr>
    <th>Description</th>
    <th>Name</th>
    <th>Status</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ads.each do |ad| %>
  <tr>
    <td><%= ad.description %></td>
    <td><%= ad.name %></td>
    <td><%= ad.state_name %></td>
    <td><%= get_name_of_type(@types, ad.ads_type_id.to_i)%></td>
    <td><%= link_to 'Show', ad %></td>
    <td><%= link_to 'Destroy', ad, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @ads %>
<br />

app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<h1>Listing ads</h1>


<% @ads.each do |ad| %>
	<div class="ad">
		<h2><%= link_to ad.name, ad %></h2>
		<%= ad.description %><br>
		Type: <%= get_name_of_type(@types, ad.ads_type_id.to_i)%> <br>
		Actions: <%= link_to 'Show', ad %>
		<%= link_to 'Edit', edit_ad_path(ad) if can? :update, ad%>
		<%= link_to 'Destroy', ad, :method => :delete, :data => { :confirm => 'Are you sure?' } if can? :delete, ad %>			
	</div>
<% end %>	

<%= will_paginate @ads %>
<br />
<%= link_to 'New Ad', new_ad_path if can? :create, Ad %>

app/views/ads/myads.html.erb
<h1>Listing your ads</h1>

<table border="1">
  <tr>
    <th>Description</th>
    <th>Name</th>
    <th>Status</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ads.each do |ad| %>
  <tr>
    <td><%= ad.description %></td>
    <td><%= ad.name %></td>
    <td><%= ad.state_name %></td>
    <td><%= get_name_of_type(@types, ad.ads_type_id.to_i)   %></td>
    <td><%= link_to 'Show', ad %></td>
    <td><%= link_to 'Edit', edit_ad_path(ad) if can? :update, ad %></td>
    <td><%= link_to 'Destroy', ad, :method => :delete if can? :destroy, ad %></td>
    <td><%= link_to 'send admin to approve', user_actions_to_new_path(:id => ad.id) if ad.can_to_new? %></td>
    <td><%= link_to 'move to drafts', user_actions_to_draft_path(:id => ad.id) if ad.can_to_draft? %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @ads %>
<br />
<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/new_ads.html.erb
<h1>Listing new ads</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Name</th>
    <th>Status</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ads.each do |ad| %>
  <tr>
    <td><%= ad.description %></td>
    <td><%= ad.name %></td>
    <td><%= ad.state_name %></td>
    <td><%= get_name_of_type(@types, ad.ads_type_id.to_i)%></td>
    <td><%= link_to 'Show', ad %></td>
    <td><%= link_to 'Deny', admin_actions_deny_path(:id => ad.id) %></td>
    <td><%= link_to 'Approve', admin_actions_approve_path(:id => ad.id) %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @ads %>
<br />

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <% @ad.images.each  do |image| %>
    <%= image_tag(image, size:'250x250') %>
  <% end %>
</p>
<p>
  <b>Description:</b>
  <%= @ad.description %>
</p>

<p>
  <b>Name:</b>
  <%= @ad.name %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) if can? :update, @ad %>
<%= link_to 'Back', ads_path %>
<% if current_user.try(:admin?)  %>
	<%= link_to 'Deny', admin_actions_deny_path(:id => @ad.id) if @ad.can_deny? %>
    <%= link_to 'Approve', admin_actions_approve_path(:id => @ad.id) if @ad.can_approve? %>
<% elsif current_user.try(:user?)  %>
	<%= link_to 'send admin to approve', user_actions_to_new_path(:id => @ad.id) if @ad.can_to_new? %>
    <%= link_to 'move to drafts', user_actions_to_draft_path(:id => @ad.id) if @ad.can_to_draft? %>
<% end %>