config/routes.rb
Rails.application.routes.draw do
  root to: 'ads#index'

  get "ads/new_ads"
  get "ads/archive_ads"
  get "ads/approved_ads"
  get "admin_actions/deny"
  get "admin_actions/approve"
  get "user_actions/to_draft"
  get "user_actions/to_new"
  get "ads/myads", to: "ads#myads"

  devise_for :users
  resources :users
  resources :ads
  resources :ads_types
end

app/controllers/ads_types_controller.rb
class AdsTypesController < ApplicationController
  load_and_authorize_resource param_method: :ads_type_params

  def index
    @ads_types = AdsType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ads_types }
    end
  end

  def show
    @ads_type = AdsType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ads_type }
    end
  end

  def new
    @ads_type = AdsType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ads_type }
    end
  end

  def edit
    @ads_type = AdsType.find(params[:id])
  end

  def create
    @ads_type = AdsType.new(params[:ads_type])

    respond_to do |format|
      if @ads_type.save
        format.html { redirect_to  @ads_type, :notice => 'Ads type was successfully created.' }
        format.json { render :json => @ads_type, :status => :created, :location => @ads_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ads_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @ads_type = AdsType.find(params[:id])

    respond_to do |format|
      if @ads_type.update_attributes(params[:ads_type])
        format.html { redirect_to @ads_type, :notice => 'Ads type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ads_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @ads_type = AdsType.find(params[:id])
    respond_to do |format|
      if @ads_type.destroy
        format.html { redirect_to ads_types_url }
      else
        format.html { redirect_to ads_types_url,  :notice => 'Cannot delete last ads type' }
      end
    end
  end

  private
  def ads_type_params
    params.require(:ads_type).permit(:name)
  end
end

app/views/ads_types/_form.html.erb
<%= form_for(@ads_type) do |f| %>
  <% if @ads_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ads_type.errors.count, "error") %> prohibited this ads_type from being saved:</h2>

      <ul>
      <% @ads_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ads_types/edit.html.erb
<h1>Editing ads_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @ads_type %> |
<%= link_to 'Back', ads_types_path %>

app/views/ads_types/index.html.erb
<h1>Listing ads_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ads_types.each do |ads_type| %>
  <tr>
    <td><%= ads_type.name %></td>
    <td><%= link_to 'Edit', edit_ads_type_path(ads_type) if can? :update, ads_type %></td>
    <td><%= link_to 'Destroy', ads_type, :data => { :confirm => 'Are you sure?' }, :method => :delete if(can?(:delete, ads_type) && ads_type.check_ads_count) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ads type', new_ads_type_path if can? :create, AdsType %>

app/views/ads_types/new.html.erb
<h1>New ads_type</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_types_path %>

app/views/ads_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ads_type.name %>
</p>


<%= link_to 'Edit', edit_ads_type_path(@ads_type) if can? :update, @ad  %> |
<%= link_to 'Back', ads_types_path %>